version: 2
jobs:
  build:
    docker:
      - image: circleci/builder-base
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push the builder image
          command: |
            TAG=$CIRCLE_BUILD_NUM
            IMAGENAME="elexy/ruby-node-gke-helm:$TAG"

            docker login --help
            docker login --username $DOCKER_USER --password $DOCKER_PWD

            echo "Building container image with name: $IMAGENAME"
            docker build -t $IMAGENAME .

            echo "running [docker push $IMAGENAME]"
            docker push $IMAGENAME